version: '3.8'
services:
    app:
        build: .
        ports:
        - "8000:8000"
        environment:
        - PYTHONPATH=/app
        - MONGODB_URL=mongodb://mongodb:27017
        - MONGODB_DATABASE=stock_market_db
        depends_on:
        - mongodb
        volumes:
        - .:/app
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
    mongodb:
        image: mongo:7.0
        ports:
        - "27017:27017"
        environment:
        - MONGO_INITDB_DATABASE=stock_market_db
        volumes:
        - mongodb_data:/data/db
        restart: unless-stopped

volumes:
    mongodb_data:
